// GENERATED by tools/build_web.py from web/report.html, field.js and game.js.
// Edit those, then run `python3 tools/build_web.py`.
//
// Self-contained: no CDN, no network, opens from a file on any laptop at a
// competition. auton_check replaces the REPORT_DATA marker with the run's JSON.
//
// In pieces because one string literal this long is past what compilers have
// to accept (MSVC stops at 16 KB a literal).
#pragma once

#include <string>

inline const char* const kReportTemplateParts[] = {
R"HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>auton check</title>
<style>
  :root {
    --bg: #0f1114; --panel: #14171b; --raise: #1b1f25; --line: #252a31;
    --ink: #e7eaee; --ink2: #a6aeb8; --muted: #6c7480;
    --amber: #f5b800; --cyan: #1fc8f0; --red: #d8423b; --blue: #2f7fd8; --late: #e5534b;
    --mono: ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace;
    --sans: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  }
  * { box-sizing: border-box; }
  [hidden] { display: none !important; }
  html, body { margin: 0; height: 100%; background: var(--bg); color: var(--ink); font: 13px/1.4 var(--sans); }
  button, select { font: inherit; color: inherit; }
  #app { display: grid; grid-template-rows: 44px 1fr 72px; grid-template-columns: minmax(0, 1fr); height: 100vh; }

  header { display: flex; align-items: center; gap: 14px; padding: 0 14px; border-bottom: 1px solid var(--line); background: var(--panel); min-width: 0; }
  .name { font: 600 13px var(--mono); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .sub { color: var(--muted); font: 12px var(--mono); white-space: nowrap; }
  .grow { flex: 1; }
  .stats { font: 12px var(--mono); color: var(--ink2); white-space: nowrap; display: flex; gap: 14px; }
  .stats b { color: var(--ink); font-weight: 600; }
  .stats .bad b { color: var(--late); }
  .chip { border: 1px solid var(--line); border-radius: 4px; padding: 0 5px; }
  .chip.ok { color: var(--ink); border-color: #3a4a3a; }
  .chip.miss { color: var(--amber); border-color: #4a3d12; }
  #code .bd.ok { color: var(--ink2); }
  .seg { display: inline-flex; border: 1px solid var(--line); border-radius: 6px; overflow: hidden; }
  .seg button { background: none; border: 0; padding: 3px 9px; color: var(--ink2); cursor: pointer; font: 12px var(--mono); }
  .seg button + button { border-left: 1px solid var(--line); }
  .seg button.on { background: var(--raise); color: var(--ink); }
  .seg button.red.on { color: #fff; background: var(--red); }
  .seg button.blue.on { color: #fff; background: var(--blue); }
  select { background: var(--panel); border: 1px solid var(--line); border-radius: 6px; padding: 3px 6px; font: 12px var(--mono); color: var(--ink2); }

  main { display: grid; grid-template-columns: minmax(0, 1fr) 360px; min-height: 0; }
  #stage { position: relative; min-width: 0; min-height: 0; display: grid; place-items: center; overflow: hidden; }
  #field { display: block; cursor: default; touch-action: none; }
  #hud { position: absolute; left: 12px; bottom: 10px; font: 12px var(--mono); color: var(--ink2); pointer-events: none; display: flex; gap: 14px; text-shadow: 0 1px 2px #000; }
  #hud b { color: var(--ink); font-weight: 500; }
  #note { position: absolute; top: 10px; left: 50%; transform: translateX(-50%); max-width: calc(100% - 24px); display: flex; gap: 10px; align-items: center;
          font: 12px var(--mono); color: var(--amber); background: rgba(20,23,27,0.92); border: 1px solid #4a3d12; border-radius: 6px; padding: 5px 10px; flex-wrap: wrap; justify-content: center; row-gap: 4px; }
  #note > * { white-space: nowrap; }
  #note code { color: var(--ink); }
  #note button { background: none; border: 1px solid #4a3d12; border-radius: 4px; color: var(--amber); padding: 1px 7px; cursor: pointer; font: 11px var(--mono); }
  #hint { position: absolute; font: 11px var(--mono); color: var(--ink); background: rgba(20,23,27,0.9); border: 1px solid var(--line); border-radius: 4px; padding: 2px 6px; pointer-events: none; white-space: nowrap; }

  aside { border-left: 1px solid var(--line); background: var(--panel); display: grid; grid-template-rows: 1fr auto; min-height: 0; }
  #code { list-style: none; margin: 0; padding: 4px 0; overflow-y: auto; font: 12px/1.25 var(--mono); }
  #code li { display: grid; grid-template-columns: 40px 12px minmax(0, 1fr) auto; gap: 6px; align-items: center; padding: 3px 10px 3px 0; cursor: pointer; border-left: 2px solid transparent; }
  #code li:hover { background: var(--raise); }
  #code li.on { background: #222019; border-left-color: var(--amber); }
  #code li.sel { background: #10242b; border-left-color: var(--cyan); }
  #code .ln { color: var(--muted); text-align: right; }
  #code .tx { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; color: var(--ink); }
  #code .k-wait .tx, #code .k-delay .tx, #code .k-set .tx { color: var(--ink2); }
  #code .k-action .tx { color: #b9c3cc; }
  #code .done .tx { opacity: 0.55; }
  #code .g { width: 7px; height: 7px; border-radius: 1px; justify-self: center; }
  #code .k-motion .g { background: var(--amber); }
  #code .k-action .g { background: var(--cyan); transform: rotate(45deg); width: 6px; height: 6px; }
  #code .bd { font-size: 11px; color: var(--muted); white-space: nowrap; }
  #code .bd.warn { color: var(--amber); }
  #code .bd.late { color: var(--late); }
  #why { border-top: 1px solid var(--line); padding: 8px 12px 10px; font: 11px/1.6 var(--mono); color: var(--ink2); }
  #why .row { display: grid; grid-template-columns: 58px 1fr; gap: 6px; }
  #why .k { color: var(--muted); }

  footer { display: grid; grid-template-columns: auto auto minmax(0, 1fr) auto; gap: 12px; align-items: center; padding: 0 14px; border-top: 1px solid var(--line); background: var(--panel); }
  #play { width: 30px; height: 30px; border-radius: 50%; border: 1px solid var(--line); background: var(--raise); cursor: pointer; display: grid; place-items: center; }
  #clock { font: 600 15px var(--mono); min-width: 64px; font-variant-numeric: tabular-nums; }
  #tl { width: 100%; height: 56px; display: block; cursor: pointer; touch-action: none; }
  #speed { background: none; border: 1px solid var(--line); border-radius: 6px; padding: 3px 8px; cursor: pointer; font: 12px var(--mono); color: var(--ink2); }
  #tip { position: fixed; pointer-events: none; font: 11px var(--mono); background: #0b0d10; border: 1px solid var(--line); border-radius: 4px; padding: 3px 7px; color: var(--ink); display: none; z-index: 5; white-space: nowrap; }

  @media (max-width: 860px) {
    #app { grid-template-rows: auto 1fr 72px; }
    header { flex-wrap: wrap; padding: 6px 12px; row-gap: 6px; white-space: normal; }
    .stats { flex-wrap: wrap; row-gap: 2px; }
    .stats > span { white-space: nowrap; }
    main { grid-template-columns: 1fr; grid-template-rows: minmax(300px, 1fr) 220px; }
    aside { border-left: 0; border-top: 1px solid var(--line); }
  }
</style>
</head>
<body>
<div id="app">
  <header>
    <span class="name" id="name"></span>
    <span class="sub" id="sub"></span>
    <span class="grow"></span>
    <select id="layout" title="field"></select>
    <span class="seg" id="side" title="alliance (mirrors the routine)"><button class="red" data-v="red">red</button><button class="blue" data-v="blue">blue</button></span>
    <span class="seg" id="units" title="units"><button data-v="in">in</button><button data-v="tiles">tiles</button></span>
    <span class="stats" id="stats"></span>
  </header>
  <main>
    <section id="stage"><canvas id="field"></canvas><div id="hud"></div><div id="note" hidden></div><div id="hint" hidden></div></section>
    <aside><ol id="code"></ol><div id="why"></div></aside>
  </main>
  <footer>
    <button id="play" title="play / pause (space)"><svg width="12" height="12" viewBox="0 0 12 12"><path id="playIcon" d="M2 1l9 5-9 5z" fill="currentColor"/></svg></button>
    <span id="clock">0.00</span>
    <canvas id="tl"></canvas>
    <button id="speed" title="playback speed">1×</button>
  </footer>
</div>
<div id="tip"></div>
<script>
// field.js: draws a VRC field and robots on a <canvas>.
//
// Shared by the auton_check report and the live sim dashboard. Plain script,
// no dependencies; exposes window.VexField.
//
// Frame: the VEX GPS / path.jerryio convention. Origin at field centre,
// inches, +x toward the blue alliance station (right), +y up the page,
// heading in degrees clockwise from +y. The red alliance station is on the
// left in every layout here, matching the game manuals' top views.
//
// Element positions come from each game manual's Figure FO-1 and the
// coordinates VEX publishes for its VR playgrounds (converted from mm). They
// are meant to be right to about an inch: good for "does my path hit the
// goal", not a substitute for field specs in Appendix A.
(function () {
  "use strict";

  const TILE = 24;            // in
  const HALF = 72;            // half the 12 ft field
  const RED = "#d8423b", BLUE = "#2f7fd8";

  // ---------------------------------------------------------------- layouts
  // A ring position is a stack, colours listed bottom first: "r" is one red
  // ring, "rb" a blue on top of a red, "rbrb" the four-high corner stacks.
  const ring = (x, y, c) => ({ x, y, c });

  // High Stakes (2024-25), Head-to-Head match.
  const HS_MATCH = {
    name: "High Stakes",
    tape: [
      // autonomous line: a pair of lines down the middle
      { a: [-1.5, -HALF], b: [-1.5, HALF] }, { a: [1.5, -HALF], b: [1.5, HALF] },
      // starting lines, parallel to each alliance station
      { a: [-58, -HALF], b: [-58, HALF] }, { a: [58, -HALF], b: [58, HALF] },
    ],
    ladder: true,
    goals: [[-24, 24], [24, 24], [-24, -24], [24, -24], [0, -48]].map(([x, y]) => ({ x, y, shape: "hex" })),
    stakes: [
      { x: -HALF, y: 0, c: RED }, { x: HALF, y: 0, c: BLUE },
      { x: 0, y: HALF, c: "#d9b33a" }, { x: 0, y: -HALF, c: "#d9b33a" },
    ],
    corners: [
      { x: -HALF, y: HALF, sign: "−" }, { x: HALF, y: HALF, sign: "−" },
      { x: -HALF, y: -HALF, sign: "+" }, { x: HALF, y: -HALF, sign: "+" },
    ],
    // Figure FO-2 (v2.0): 8 single rings, 10 stacks of two, 4 corner stacks of
    // four = 44, plus 4 preloads = the 48 in the manual.
    rings: [
      ring(-24, 48, "rb"), ring(24, 48, "br"),
      ring(-3.5, 51.5, "rb"), ring(-3.5, 44.5, "rb"), ring(3.5, 51.5, "br"), ring(3.5, 44.5, "br"),
      ring(-3.5, 3.5, "b"), ring(-3.5, -3.5, "b"), ring(3.5, 3.5, "r"), ring(3.5, -3.5, "r"),
      ring(-58, 0, "b"), ring(-47, 0, "br"), ring(47, 0, "rb"), ring(58, 0, "r"),
      ring(-47, -48, "b"), ring(-24, -48, "rb"), ring(24, -48, "br"), ring(47, -48, "r"),
      ring(-67, 67, "rbrb"), ring(-67, -67, "rbrb"), ring(67, 67, "brbr"), ring(67, -67, "brbr"),
    ],
  };

  // High Stakes Robot Skills layout (manual p.72, VEX VR playground).
  const HS_SKILLS = Object.assign({}, HS_MATCH, {
    name: "High Stakes skills",
    goals: [[-48, 24], [-48, -24], [48, 0], [60, 24], [60, -24]].map(([x, y]) => ({ x, y, shape: "hex" })),
    rings: [
      ...[[-48, 60], [0, 60], [-60, 48], [-48, 48], [24, 48], [-24, 24], [24, 24], [0, 0], [-24, -24],
          [24, -24], [-60, -48], [-48, -48], [24, -48], [-48, -60], [0, -60]].map(([x, y]) => ring(x, y, "r")),
      ...[[48, 60], [48, 48], [60, 48], [48, -48], [60, -48], [48, -60]].map(([x, y]) => ring(x, y, "br")),
      ring(67, 67, "b"), ring(67, -67, "b"),
    ],
  });

  // Override (2026-27), Head-to-Head match.
  const OV_MATCH = {
    name: "Override",
    tape: [
      // the midfield square, corner-on
      { a: [0, 24], b: [24, 0] }, { a: [24, 0], b: [0, -24] }, { a: [0, -24], b: [-24, 0] }, { a: [-24, 0], b: [0, 24] },
      // diagonals from the corners into the midfield (doubled on one axis)
      { a: [-58.5, 58.5], b: [-12, 12], double: true }, { a: [12, -12], b: [58.5, -58.5], double: true },
      { a: [58.5, 58.5], b: [12, 12] }, { a: [-58.5, -58.5], b: [-12, -12] },
    ],
    zones: [
      // alliance corner zones (coloured tape)
      { c: RED, pts: [[-59, HALF], [-59, 46], [-HALF, 46]] }, { c: RED, pts: [[-59, -HALF], [-59, -46], [-HALF, -46]] },
      { c: BLUE, pts: [[59, HALF], [59, 46], [HALF, 46]] }, { c: BLUE, pts: [[59, -HALF], [59, -46], [HALF, -46]] },
    ],
    goals: [
      ...[[0, 0], [-24, 48], [-48, 24], [48, -24], [24, -48]].map(([x, y]) => ({ x, y, s)HTML",
R"HTML(hape: "oct" })),
      ...[[-48, -24], [-24, -48]].map(([x, y]) => ({ x, y, shape: "oct", c: RED })),
      ...[[24, 48], [48, 24]].map(([x, y]) => ({ x, y, shape: "oct", c: BLUE })),
    ],
    toggles: [{ x: 0, y: HALF, h: true }, { x: 0, y: -HALF, h: true }, { x: -HALF, y: 0 }, { x: HALF, y: 0 }],
    loaders: [[-HALF, 58.7], [-HALF, -58.7], [HALF, 58.7], [HALF, -58.7]],
    pins: [[-24, 68.7], [24, 68.7], [-48, 48], [48, 48], [-68.7, 24], [-24, 24], [0, 24], [24, 24], [68.7, 24],
           [-24, 0], [24, 0], [-68.7, -24], [-24, -24], [0, -24], [24, -24], [68.7, -24], [-48, -48], [48, -48],
           [-24, -68.7], [24, -68.7]],
  };

  const BLANK = { name: "Tiles only" };

  const LAYOUTS = { "high-stakes": HS_MATCH, "high-stakes-skills": HS_SKILLS, override: OV_MATCH, blank: BLANK };

  // ---------------------------------------------------------------- view
  // A view maps field inches onto canvas pixels. `extent` is the half-width
  // in inches shown, wide enough to include the alliance stations.
  function view(sizePx, extent) {
    const ext = extent || 82;
    const s = sizePx / (2 * ext);
    return {
      s, size: sizePx, ext,
      px: (x, y) => [sizePx / 2 + x * s, sizePx / 2 - y * s],
      inches: (px, py) => [(px - sizePx / 2) / s, (sizePx / 2 - py) / s],
    };
  }

  // ---------------------------------------------------------------- drawing
  const C = {
    floor: "#0f1114", tile: "#4f535a", seam: "#3f4248", wall: "#c7cbd1", wallEdge: "#8d939b",
    tape: "rgba(245,245,245,0.92)", ring: { r: "#d8423b", b: "#2f7fd8" }, goal: "#d9b33a",
    ladder: "#24272c", ladderRail: "#9aa1aa", toggle: "#d24fa8", pin: "#d9b33a", loader: "#e9ecef",
  };

  // opts.elements === false leaves out goals and rings (and the rings on
  // stakes), for pages that animate them with drawElements().
  function drawField(ctx, V, layoutKey, opts) {
    const L = LAYOUTS[layoutKey] || HS_MATCH;
    const withElements = !opts || opts.elements !== false;
    const s = V.s;
    const P = V.px;
    ctx.save();
    ctx.fillStyle = C.floor;
    ctx.fillRect(0, 0, V.size, V.size);

    // alliance stations, outside the left and right walls
    for (const [side, col] of [[-1, RED], [1, BLUE]]) {
      const [x0] = P(side * (HALF + 4), 0);
      const [x1] = P(side * (HALF + 7.5), 0);
      const [, yTop] = P(0, 46), [, yBot] = P(0, -46);
      ctx.fillStyle = col;
      ctx.globalAlpha = 0.85;
      ctx.fillRect(Math.min(x0, x1), yTop, Math.abs(x1 - x0), yBot - yTop);
      ctx.globalAlpha = 1;
    }

    // tiles
    const [fx, fy] = P(-HALF, HALF);
    const fw = 2 * HALF * s;
    ctx.fillStyle = C.tile;
    ctx.fillRect(fx, fy, fw, fw);
    ctx.strokeStyle = C.seam;
    ctx.lineWidth = Math.max(1, 0.35 * s);
    for (let i = 1; i < 6; i++) {
      const g = fx + i * TILE * s;
      line(ctx, g, fy, g, fy + fw);
      const h = fy + i * TILE * s;
      line(ctx, fx, h, fx + fw, h);
    }

    // tape
    ctx.strokeStyle = C.tape;
    ctx.lineCap = "butt";
    ctx.lineWidth = Math.max(1, 1 * s);
    for (const t of L.tape || []) {
      if (t.double) {
        const dx = t.b[0] - t.a[0], dy = t.b[1] - t.a[1], n = Math.hypot(dx, dy);
        const ox = (-dy / n) * 1.6, oy = (dx / n) * 1.6;
        for (const k of [-1, 1]) segIn(ctx, P, t.a[0] + k * ox, t.a[1] + k * oy, t.b[0] + k * ox, t.b[1] + k * oy);
      } else {
        segIn(ctx, P, t.a[0], t.a[1], t.b[0], t.b[1]);
      }
    }
    for (const z of L.zones || []) {
      ctx.strokeStyle = z.c;
      ctx.lineWidth = Math.max(1.5, 1.2 * s);
      ctx.beginPath();
      z.pts.forEach(([x, y], i) => { const [px, py] = P(x, y); i ? ctx.lineTo(px, py) : ctx.moveTo(px, py); });
      ctx.stroke();
    }

    // corners (High Stakes): a faint triangle on the tiles, and the +/-
    // sticker where it really is, on the wall outside the corner
    for (const k of L.corners || []) {
      const sx = Math.sign(k.x), sy = Math.sign(k.y);
      ctx.fillStyle = k.sign === "+" ? "rgba(255,255,255,0.10)" : "rgba(0,0,0,0.18)";
      ctx.beginPath();
      ctx.moveTo(...P(k.x, k.y));
      ctx.lineTo(...P(k.x - sx * 15, k.y));
      ctx.lineTo(...P(k.x, k.y - sy * 15));
      ctx.closePath();
      ctx.fill();
      ctx.fillStyle = "rgba(255,255,255,0.8)";
      ctx.font = `700 ${Math.max(10, 4.5 * s)}px ui-monospace, "SF Mono", Menlo, monospace`;
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText(k.sign, ...P(k.x + sx * 5, k.y + sy * 5));
    }

    if (L.ladder) drawLadder(ctx, P, s);

    // wall stakes (High Stakes)
    for (const k of L.stakes || []) {
      const [px, py] = P(k.x, k.y);
      ctx.fillStyle = k.c;
      ctx.beginPath();
      ctx.arc(px, py, 2.2 * s, 0, Math.PI * 2);
      ctx.fill();
      ctx.strokeStyle = "rgba(0,0,0,0.5)";
      ctx.lineWidth = 1;
      ctx.stroke();
    }

    if (withElements) {
      for (const g of L.goals || []) drawGoal(ctx, V, g.x, g.y, g, []);
      for (const r of L.rings || []) drawStack(ctx, V, r.x, r.y, r.c);
    }

    // Override: pins, toggles, loaders
    for (const [x, y] of L.pins || []) {
      const [px, py] = P(x, y);
      ctx.fillStyle = C.pin;
      ctx.globalAlpha = 0.8;
      ctx.beginPath(); ctx.arc(px, py, 1.6 * s, 0, Math.PI * 2); ctx.fill();
      ctx.globalAlpha = 1;
    }
    for (const t of L.toggles || []) {
      const [px, py] = P(t.x + (t.h ? 0 : Math.sign(t.x) * 2.5), t.y + (t.h ? Math.sign(t.y) * 2.5 : 0));
      const long = 28 * s, short = 2.5 * s;
      ctx.fillStyle = C.toggle;
      if (t.h) ctx.fillRect(px - long / 2, py - short / 2, long, short);
      else ctx.fillRect(px - short / 2, py - long / 2, short, long);
    }
    for (const [x, y] of L.loaders || []) {
      const [px, py] = P(x - Math.sign(x) * 2, y);
      ctx.fillStyle = C.loader;
      ctx.globalAlpha = 0.85;
      ctx.fillRect(px - 2 * s, py - 4 * s, 4 * s, 8 * s);
      ctx.globalAlpha = 1;
    }

    // perimeter
    ctx.strokeStyle = C.wall;
    ctx.lineWidth = Math.max(2, 2 * s);
    ctx.strokeRect(fx - s, fy - s, fw + 2 * s, fw + 2 * s);
    ctx.restore();
  }

  // A ring stack seen from above, like the manual's legend: one colour for a
  // single ring, top half / bottom half for two, quarters for more. `cs` is
  // bottom first (string or array).
  function drawStack(ctx, V, x, y, cs, scale) {
    cs = Array.isArray(cs) ? cs : String(cs).split("");
    if (!cs.length) return;
    const s = V.s * (scale || 1);
    const [px, py] = V.px(x, y);
    const top = cs[cs.length - 1], under = cs.length > 1 ? cs[cs.length - 2] : top;
    ctx.save();
    ctx.lineWidth = 2.2 * s;
    const arc = (c, a0, a1) => { ctx.strokeStyle = C.ring[c] || c; ctx.beginPath(); ctx.arc(px, py, 2.4 * s, a0, a1); ctx.stroke(); };
    if (cs.length === 1) { ctx.globalAlpha = 0.9; arc(top, 0, Math.PI * 2); }
    else if (cs.length === 2) { arc(top, Math.PI, 0); arc(under, 0, Math.PI); }
    else {
      const q = Math.PI / 2;
      for (let i = 0; i < 4; i++) arc(i % 2 ? under : top, -3 * q / 2 + i * q, -q / 2 + i * q);
    }
    ctx.restore();
  }

  // A mobile goal, and the rings on its stake drawn as a short stack beside
  // the count (top ring's colour is what scores 3).
  function drawGoal(ctx, V, x, y, g, rings, opts) {
    const s = V.s;
    const [px, py] = V.px(x, y);
    const r = 5 * s;
    const n = g.shape === "oct" ? 8 : 6;
    ctx.save();
    ctx.beginPath();
    for (let i = 0; i < n; i++) {
      const a = (Math.PI * 2 * i) / n + (n === 6 ? Math.PI / 6 : Math.PI / 8);
      const X = px + r * Math.cos(a), Y = py + r * Math.sin(a);
      i ? ctx.lineTo(X, Y) : ctx.moveTo(X, Y);
    }
    ctx.closePath();
    ctx.fillStyle = g.c ? g.c : n === 6 ? C.goal : "#6c7280";
    ctx.globalAlpha = opts && opts.held ? 0.9 : 0.72;
    ctx.fill();
    ctx.globalAlpha = 1;
    ctx.lineWidth = Math.max(1, 0.5 * s);
    ctx.strokeStyle = opts && opts.held ? "#fff" : "rgba(0,0,0,0.45)";
    ctx.stroke();
    if (rings && rings.length) {
      drawStack(ctx, V, x, y, rings, 1.15);
      label(ctx, V, x, y, String(rings.length));
    } else {
      ctx.fillStyle = "rgba(0,0,0,0.55)";
      ctx.beginPath();
      ctx.arc(px, py, 0.9 * s, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.restore();
  }

  function label(ctx, V, x, y, text) {
    const [px, py] = V.px(x, y);
    ctx.save();
    ctx.font = `700 ${Math.max(9, 3.2 * V.s)}px ui-monospace, "SF Mono", Menlo, monospace`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.lineWidth = 3;
    ctx.strokeStyle = "rgba(0,0,0,0.7)";
    ctx.strokeText(text, px, py);
    ctx.fillStyle = "#fff";
    ctx.fillText(text, px, py);
    ctx.restore();
  }

  // Everything the game sim moves: loose ring stacks, goals (held or not)
  // with their rings, and rings on the wall stakes.
  // state = { loose: [{x, y, cs}], goals: [{x, y, held, rings}], stakes: [{x, y, rings}] }
  function drawElements(ctx, V, layoutKey, state) {
    const L = LAYOUTS[layoutKey] || HS_MATCH;
    (state.goals || []).forEach((g, i) => drawGoal(ctx, V, g.x, g.y, (L.goals || [])[i] || {}, g.rings, { held: g.held }));
    for (const r of state.loose || []) drawStack(ctx, V, r.x, r.y, r.cs);
    for (const k of state.stakes || []) {
      if (!k.rings.length) continue;
      drawStack(ctx, V, k.x - Math.sign(k.x) * 2.5, k.y - Math.sign(k.y) * 2.5, k.rings, 1.0);
      label(ctx, V, k.x - Math.sign(k.x) * 7, k.y - Math.sign(k.y) * 7, String(k.rings.length));
    }
  }

  function drawLadder(ctx, P, s) {
    const pts = [[0, 24], [24, 0], [0, -24], [-24, 0]];
    ctx.save();
    ctx.beginPath();
    pts.forEach(([x, y], i) => { const [px, py] = P(x, y); i ? ctx.lineTo(px, py) : ctx.moveTo(px, py); });
    ctx.closePath();
    ctx.fillStyle = "rgba(20,22,26,0.35)";
    ctx.fill();
    ctx.lineWidth = Math.max(2, 2.2 * s);
    ctx.strokeStyle = C.ladderRail;
    ctx.stroke();
    ctx.fillStyle = C.ladder;
    for (const [x, y] of pts) { ctx.beginPath(); ctx.arc(...P(x, y), 2 * s, 0, Math.PI * 2); ctx.fill(); }
    ctx.fillStyle = C.goal;                       // the High Stake on top
    ctx.beginPath(); ctx.arc(...P(0, 0), 1.6 * s, 0, Math.PI * 2); ctx.fill();
    ctx.restore();
  }

  function line(ctx, x0, y0, x1, y1) { ctx.beginPath(); ctx.moveTo(x0, y0); ctx.lineTo(x1, y1); ctx.stroke(); }
  function segIn(ctx, P, x0, y0, x1, y1) { const a = P(x0, y0), b = P(x1, y1); line(ctx, a[0], a[1], b[0], b[1]); }

  // A robot footprint: its outline (robot frame, inches, +y forward) or a
  // rounded w x l box, a thick front edge, a heading tick. opt.zones draws
  // boxes in the robot frame too (where the intake grabs, the clamp holds).
  function drawRobot(ctx, V, pose, o) {
    const opt = Object.assign({ w: 15, l: 15, fill: null, stroke: "#fff", width: 1.5, alpha: 1, front: null }, o);
    const [px, py] = V.px(pose[0], pose[1]);
    const s = V.s;
    ctx.save();
    ctx.globalAlpha = opt.alpha;
    ctx.translate(px, py);
    ctx.rotate((pose[2] * Math.PI) / 180);       // compass: clockwise from up
    const w = opt.w * s, l = opt.l * s;
    if (opt.outline && opt.outline.length >= 3) {
      ctx.beginPath();
      opt.outline.forEach(([x, y], i) => (i ? ctx.lineTo(x * s, -y * s) : ctx.moveTo(x * s, -y * s)));
      ctx.closePath();
    } else {
      roundRect(ctx, -w / 2, -l / 2, w, l, Math.min(3 * s, 4));
    }
    if (opt.fill) { ctx.fillStyle = opt.fill; ctx.fill(); }
    if (opt.stroke) { ctx.strokeStyle = opt.stroke; ctx.lineWidth = opt.width; ctx.stroke(); }
    for (const z of opt.zones || []) {
      const [[x0, y0], [x1, y1]] = z.box;
      ctx.save();
      ctx.globalAlpha = 1;
      ctx.setLineDash([3, 2]);
      ctx.lineWidth = 1;
      ctx.strokeStyle = z.color;
      ctx.strokeRect(x0 * s, -y1 * s, (x1 - x0) * s, (y1 - y0) * s);
      ctx.restore();
    }
    if (opt.front) {
      ctx.strokeStyle = opt.front;
      ctx.lineWidth = Math.max(2, opt.width * 1.8);
      ctx.beginPath(); ctx.moveTo(-w / 2 + 2, -l / 2); ctx.lineTo(w / 2 - 2, )HTML",
R"HTML(-l / 2); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(0, -l / 2); ctx.lineTo(0, -l / 2 - 4 * s); ctx.stroke();
    }
    ctx.restore();
  }

  function roundRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
  }

  // ---------------------------------------------------------------- frames
  // Re-express a pose from a routine's own frame (whatever odom_xyt_set
  // declared) on the field, given where its start pose sits on the field.
  function codeToField(p, codeStart, place) {
    const phi = ((place[2] - codeStart[2]) * Math.PI) / 180;   // clockwise
    const dx = p[0] - codeStart[0], dy = p[1] - codeStart[1];
    return [place[0] + dx * Math.cos(phi) + dy * Math.sin(phi),
            place[1] - dx * Math.sin(phi) + dy * Math.cos(phi),
            p[2] + (place[2] - codeStart[2])];
  }

  // The same routine run from the other alliance: reflect across the field's
  // centre line. EZ autons mirror this way when every turn is `* sgn`.
  const mirror = (p) => [-p[0], p[1], -p[2]];

  // ---------------------------------------------------------------- units
  function fmtLen(inches, units, digits) {
    if (units === "tiles") return (inches / TILE).toFixed(digits == null ? 2 : digits) + "t";
    return inches.toFixed(digits == null ? 1 : digits) + "″";
  }
  const wrapDeg = (a) => { a = ((a + 180) % 360 + 360) % 360 - 180; return a <= -180 ? 180 : a; };

  window.VexField = {
    TILE, HALF, RED, BLUE, LAYOUTS, view, drawField, drawElements, drawStack, drawRobot, codeToField, mirror, fmtLen, wrapDeg,
  };
})();
</script>
<script>
// game.js: what a routine does to the game elements, and what it scores.
//
// Runs over a robot trajectory that's already been simulated (auton_check's
// clean run and its varied runs), so it's cheap enough to redo every time the
// start position is dragged. Mechanisms come from robot.json (see
// docs/robot_spec.md): where the intake grabs, where the clamp holds a goal,
// how far the arm reaches, and which action("...") lines drive them.
//
// High Stakes only for now. Deliberately rough: the robot drives through goals
// and rings instead of pushing them, rings teleport up the conveyor at a fixed
// rate, the arm swings at a fixed speed. Good for "does the clamp fire with a
// goal under it" and "does this score 7 or 3", not for ring physics.
//
// Frame: field inches, +x toward blue, +y up, heading clockwise from +y
// (same as field.js). Robot frame: +x right, +y forward, origin at the centre
// of the drivetrain.
(function (root) {
  "use strict";

  const HALF = 72;
  const RING_ON = 0.2;          // |intake speed| below this doesn't move rings
  const DT = 0.02;              // s
  const GOAL_R = 5;             // mobile goal base, centre to flat-ish (in)
  const RING_R = 3.5;           // ring outer radius (7 in across)

  // ---------------------------------------------------------------- field
  // Starting elements per layout. Rings carry a stack (bottom first).
  const LAYOUTS = {
    "high-stakes": {
      // same stacks as field.js (Figure FO-2), bottom ring first
      rings: [
        [-24, 48, "rb"], [24, 48, "br"],
        [-3.5, 51.5, "rb"], [-3.5, 44.5, "rb"], [3.5, 51.5, "br"], [3.5, 44.5, "br"],
        [-3.5, 3.5, "b"], [-3.5, -3.5, "b"], [3.5, 3.5, "r"], [3.5, -3.5, "r"],
        [-58, 0, "b"], [-47, 0, "br"], [47, 0, "rb"], [58, 0, "r"],
        [-47, -48, "b"], [-24, -48, "rb"], [24, -48, "br"], [47, -48, "r"],
        [-67, 67, "rbrb"], [-67, -67, "rbrb"], [67, 67, "brbr"], [67, -67, "brbr"],
      ],
      goals: [[-24, 24], [24, 24], [-24, -24], [24, -24], [0, -48]],
      stakes: [
        { x: -HALF, y: 0, only: "r", cap: 2 }, { x: HALF, y: 0, only: "b", cap: 2 },
        { x: 0, y: HALF, cap: 6 }, { x: 0, y: -HALF, cap: 6 },
      ],
      corners: [[-HALF, HALF, -1], [HALF, HALF, -1], [-HALF, -HALF, 1], [HALF, -HALF, 1]],
      startingLine: 58,
      match: true,
    },
    "high-stakes-skills": {
      rings: [
        ...[[-48, 60], [0, 60], [-60, 48], [-48, 48], [24, 48], [-24, 24], [24, 24], [0, 0], [-24, -24],
            [24, -24], [-60, -48], [-48, -48], [24, -48], [-48, -60], [0, -60]].map(([x, y]) => [x, y, "r"]),
        ...[[48, 60], [48, 48], [60, 48], [48, -48], [60, -48], [48, -60]].map(([x, y]) => [x, y, "br"]),
        [67, 67, "b"], [67, -67, "b"],
      ],
      goals: [[-48, 24], [-48, -24], [48, 0], [60, 24], [60, -24]],
      stakes: [
        { x: -HALF, y: 0, only: "r", cap: 2 }, { x: HALF, y: 0, only: "b", cap: 2 },
        { x: 0, y: HALF, cap: 6 }, { x: 0, y: -HALF, cap: 6 },
      ],
      corners: [[-HALF, HALF, -1], [HALF, HALF, -1], [-HALF, -HALF, 1], [HALF, -HALF, 1]],
      startingLine: 58,
      match: false,
    },
  };
  const supported = (key) => Object.prototype.hasOwnProperty.call(LAYOUTS, key);

  // ---------------------------------------------------------------- geometry
  function toRobot(pose, x, y) {           // field point -> robot frame
    const th = (pose[2] * Math.PI) / 180, dx = x - pose[0], dy = y - pose[1];
    return [dx * Math.cos(th) - dy * Math.sin(th), dx * Math.sin(th) + dy * Math.cos(th)];
  }
  function toField(pose, rx, ry) {         // robot frame point -> field
    const th = (pose[2] * Math.PI) / 180;
    return [pose[0] + rx * Math.cos(th) + ry * Math.sin(th), pose[1] - rx * Math.sin(th) + ry * Math.cos(th)];
  }
  const inBox = (p, z, pad) => p[0] >= z[0][0] - pad && p[0] <= z[1][0] + pad && p[1] >= z[0][1] - pad && p[1] <= z[1][1] + pad;
  const boxCentre = (z) => [(z[0][0] + z[1][0]) / 2, (z[0][1] + z[1][1]) / 2];
  const normBox = (z) => [[Math.min(z[0][0], z[1][0]), Math.min(z[0][1], z[1][1])], [Math.max(z[0][0], z[1][0]), Math.max(z[0][1], z[1][1])]];

  // Is a goal "Placed" in a corner? Its centre inside the corner triangle
  // (legs of about 17 in, which is where a goal base sits once it's pushed in).
  function cornerOf(L, x, y) {
    for (const [cx, cy, sign] of L.corners) if (Math.abs(cx - x) + Math.abs(cy - y) < 17) return sign;
    return 0;
  }

  // ---------------------------------------------------------------- robot
  // Fill in what robot.json leaves out, so a half-finished spec still runs.
  function compile(spec) {
    spec = spec || {};
    const fp = spec.footprint || {};
    const w = fp.width || 15, l = fp.length || 15;
    const outline = Array.isArray(spec.outline) && spec.outline.length >= 3 ? spec.outline
      : [[-w / 2, -l / 2], [w / 2, -l / 2], [w / 2, l / 2], [-w / 2, l / 2]];
    const mechs = {};
    for (const m of spec.mechanisms || []) if (m && m.id) mechs[m.id] = m;
    const byKind = (k) => Object.values(mechs).find((m) => m.kind === k);

    const intake = byKind("intake");
    const clamp = byKind("goal_clamp");
    const arm = byKind("wall_stake_arm");
    const sorter = byKind("color_sort");
    const R = {
      name: spec.name || "robot", w, l, outline,
      intake: intake && {
        id: intake.id,
        zone: normBox(intake.zone || [[-w / 2 + 2, l / 2 - 2], [w / 2 - 2, l / 2 + 3]]),
        capacity: intake.capacity || 2,
        transfer: intake.transfer_s || 0.6,       // s for a ring to go from the floor to the top
        pickGap: intake.pickup_gap_s || 0.15,
      },
      clamp: clamp && {
        id: clamp.id,
        zone: normBox(clamp.zone || [[-4, -l / 2 - 4], [4, -l / 2 + 2]]),
        closedWhen: clamp.closed_when === undefined ? true : !!clamp.closed_when,
      },
      arm: arm && {
        id: arm.id,
        states: arm.states || {},
        load: arm.load_state || "PROPPED",
        scoreDeg: arm.score_deg || 120,
        dps: arm.deg_per_s || 280,
        reach: normBox(arm.reach || [[-4, l / 2], [4, l / 2 + 11]]),
        start: arm.start,
      },
      sorter: sorter && { id: sorter.id, start: !!sorter.start },
      mechs,
      bindings: [],
    };
    // Explicit bindings first, then the obvious ones from each mechanism's
    // names in the code (intake.move(127), mogoClamp.toggle(), ...).
    for (const b of spec.bindings || []) {
      try { R.bindings.push({ re: new RegExp(b.match), mech: b.mech, op: b.do, value: b.value, scale: b.scale || 1 }); }
      catch (e) { /* a bad regex in robot.json just doesn't bind */ }
    }
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    for (const m of Object.values(mechs)) {
      for (const n of m.code_names || []) {
        const N = esc(n);
        if (m.actuator === "pneumatic") {
          R.bindings.push({ re: new RegExp(`^${N}\\.toggle\\(\\)$`), mech: m.id, op: "toggle" });
          R.bindings.push({ re: new RegExp(`^${N}\\.(extend|retract)\\(\\)$`), mech: m.id, op: "set", value: "$1" });
          R.bindings.push({ re: new RegExp(`^${N}\\.set_value\\((.+)\\)$`), mech: m.id, op: "set", value: "$1" });
        } else {
          R.bindings.push({ re: new RegExp(`^${N}\\.move\\((.+)\\)$`), mech: m.id, op: "speed", value: "$1", scale: 127 });
          R.bindings.push({ re: new RegExp(`^${N}\\.move_voltage\\((.+)\\)$`), mech: m.id, op: "speed", value: "$1", scale: 12000 });
          R.bindings.push({ re: new RegExp(`^${N}\\.move_velocity\\((.+)\\)$`), mech: m.id, op: "speed", value: "$1", scale: m.cartridge_rpm || 600 });
          R.bindings.push({ re: new RegExp(`^${N}\\.brake\\(\\)$`), mech: m.id, op: "speed", value: "0" });
        }
      }
    }
    return R;
  }

  // Numbers in action text: "127", "-127", "45 + 10", "12000 * 0.8". Anything
  // fancier isn't a number we can know ahead of time.
  function evalNumber(s) {
    s = String(s).trim();
    if (!/^[-+*/(). \d]+$/.test(s)) return NaN;
    let i = 0;
    const peek = () => s[i], ws = () => { while (s[i] === " ") i++; };
    function atom() {
      ws();
      if (peek() === "(") { i++; const v = expr(); ws(); i++; return v; }
      if (peek() === "-") { i++; return -atom(); }
      if (peek() === "+") { i++; return atom(); }
      const m = /^\d+(\.\d+)?|^\.\d+/.exec(s.slice(i));
      if (!m) return NaN;
      i += m[0].length;
      return parseFloat(m[0]);
    }
    function term() { let v = atom(); for (ws(); peek() === "*" || peek() === "/"; ws()) { const o = s[i++]; const r = atom(); v = o === "*" ? v * r : v / r; } return v; }
    function expr() { let v = term(); for (ws(); peek() === "+" || peek() === "-"; ws()) { const o = s[i++]; const r = term(); v = o === "+" ? v + r : v - r; } return v; }
    const v = expr();
    ws();
    return i === s.length ? v : NaN;
  }

  // action("...") lines -> mechanism events, in time order. `times[k]` is when
  // action k fired in this run (-1 if it never did).
  function events(R, actionTexts, times) {
    const out = [];
    actionTexts.forEach((text, k) => {
      const t = times[k];
      if (!(t >= 0)) return;
      for (const b of R.bindings) {
        const m = b.re.exec(text);
        if (!m) continue;
        let v = b.value === undefined ? undefined : String(b.value).replace(/\$(\d)/g, (_, n) => m[+n] || "");
        out.push({ t, k, text, mech: b.mech, op: b.op, value: v, scale: b.scale });
        break;
      }
    });
    out.sort((a, b) => a.t - b.t || a.k - b.k);
    return out;
  }

  // ---------------------------------------------------------------- the sim
  // poseAt(t) -> [x, y, heading] in field inches. Returns a log of where every
  // element was and when, what each mechanism call did, and the score.
  function run({ layout, robot: R, alliance, poseAt, events: evs, end, budget, preload = true }) {
    const L = LAYOUTS[layout];
    if (!L) return null;
    const us = alliance === "blue" ? "b" : "r";
    const side = us === "b" ? 1 : -1;

    // elements ------------------------------------------------------------
    const rings = [];   // { c, track: [{t, at, x, y, ref}] }
    const stacks = L.rings.map(([x, y, cs]) => {
      const ids = [];
      for (const c of)HTML",
R"HTML( cs) { ids.push(rings.length); rings.push({ c, track: [{ t: 0, at: "field", x, y }] }); }
      return { x, y, ids };          // bottom first; the top is ids[ids.length - 1]
    });
    const goals = L.goals.map(([x, y]) => ({ x, y, rings: [], held: false, track: [{ t: 0, held: false, x, y }] }));
    const stakes = L.stakes.map((s) => ({ ...s, rings: [] }));
    const put = (id, t, at, x, y, ref) => rings[id].track.push({ t, at, x, y, ref });

    // robot ---------------------------------------------------------------
    const st = {
      intake: 0, queue: [],          // queue: { id, p } p = 0 floor .. 1 top
      lastPick: -1, until: 0, untilSeen: 0,
      clampClosed: false, goal: -1,
      armDeg: 0, armTarget: 0, armRing: -1, armScoredThisSwing: false,
      sort: !!(R.sorter && R.sorter.start), flags: {},
    };
    const outcome = {};              // action index -> { ok, text }
    let intakeEvent = -1;            // the call that last started the intake
    const picked = {};               // action index -> rings picked while it was in charge

    const armAngle = (v) => {
      if (!R.arm) return 0;
      if (v in R.arm.states) return R.arm.states[v];
      const n = evalNumber(v);
      return Number.isFinite(n) ? n : null;
    };

    function apply(ev, t, pose) {
      const set = (ok, text) => { outcome[ev.k] = { ok, text }; };
      const mech = R.mechs[ev.mech] || {};
      if (R.intake && ev.mech === R.intake.id) {
        if (ev.op === "speed") {
          const n = evalNumber(ev.value);
          if (!Number.isFinite(n)) { set(null, "speed unknown"); return; }
          st.intake = Math.max(-1, Math.min(1, n / (ev.scale || 1)));
          if (st.intake > RING_ON) { intakeEvent = ev.k; picked[ev.k] = 0; set(null, "intake on"); }
          else set(null, st.intake < -RING_ON ? "outtake" : "intake off");
        } else if (ev.op === "until") {
          st.until = Math.max(1, evalNumber(ev.value) || 1); st.untilSeen = 0; st.intake = 1;
          intakeEvent = ev.k; picked[ev.k] = 0; set(null, `hold ${st.until}`);
        } else if (ev.op === "release") { st.until = 0; set(null, ""); }
        return;
      }
      if (R.clamp && ev.mech === R.clamp.id) {
        let on = st.clampClosed;
        if (ev.op === "toggle") on = !on;
        else if (ev.op === "set") {
          const v = String(ev.value).trim();
          const ext = v === "extend" || v === "true" || v === "1" || v === "HIGH";
          on = ext === R.clamp.closedWhen;
        }
        if (on && !st.clampClosed) {
          // grab the nearest free goal under the clamp
          const c = boxCentre(R.clamp.zone);
          let best = -1, bestD = Infinity, nearest = Infinity;
          goals.forEach((g, i) => {
            if (g.held) return;
            const p = toRobot(pose, g.x, g.y);
            const d = Math.hypot(p[0] - c[0], p[1] - c[1]);
            nearest = Math.min(nearest, d);
            if (inBox(p, R.clamp.zone, 1.0) && d < bestD) { best = i; bestD = d; }
          });
          if (best >= 0) {
            st.goal = best; goals[best].held = true;
            set(true, "clamped");
          } else {
            set(false, nearest < 30 ? `missed, goal ${nearest.toFixed(1)}″ away` : "nothing to clamp");
          }
        } else if (!on && st.clampClosed) {
          if (st.goal >= 0) {
            const g = goals[st.goal];
            g.held = false;
            g.track.push({ t, held: false, x: g.x, y: g.y });
            const k = cornerOf(L, g.x, g.y);
            set(null, k > 0 ? "dropped in + corner" : k < 0 ? "dropped in − corner" : "released");
          } else set(null, "opened");
          st.goal = -1;
        } else set(null, on ? "already closed" : "already open");
        st.clampClosed = on;
        return;
      }
      if (R.arm && ev.mech === R.arm.id) {
        if (ev.op === "state" || ev.op === "angle") {
          const a = armAngle(ev.value);
          if (a == null) { set(null, "angle unknown"); return; }
          st.armTarget = a;
          if (ev.reset) st.armDeg = a;
          st.armEvent = ev.k;
          set(null, a >= R.arm.scoreDeg ? (st.armRing >= 0 ? "swinging" : "empty") : "");
        } else if (ev.op === "speed") {
          const n = evalNumber(ev.value);
          if (Number.isFinite(n)) st.armTarget = n > 0 ? 200 : 0;
        }
        return;
      }
      if (R.sorter && ev.mech === R.sorter.id) {
        if (ev.op === "set") st.sort = /^(true|1|on)$/.test(String(ev.value).trim());
        else if (ev.op === "toggle") st.sort = !st.sort;
        else if (ev.op === "until") { st.until = Math.max(1, evalNumber(ev.value) || 1); st.untilSeen = 0; if (R.intake) { st.intake = 1; intakeEvent = ev.k; picked[ev.k] = 0; } }
        else if (ev.op === "release") st.until = 0;
        set(null, "");
        return;
      }
      // doinkers, lifts and anything else: remembered, no effect on elements
      if (ev.op === "toggle") st.flags[ev.mech] = !st.flags[ev.mech];
      else if (ev.op === "set") st.flags[ev.mech] = /^(true|1|extend|HIGH)$/.test(String(ev.value).trim());
      set(null, mech.kind || "");
    }

    // Calls before the robot has moved (the first tick or two) describe how
    // it's set up, e.g. `LBState = PROPPED` for the preload: they apply
    // instantly. Then the preload goes in the arm if it starts at its load
    // angle, else in the intake.
    const p0 = poseAt(0);
    if (R.arm && R.arm.start !== undefined) {
      const a0 = armAngle(String(R.arm.start));
      if (a0 != null) st.armDeg = st.armTarget = a0;
    }
    let evi = 0;
    while (evi < evs.length && evs[evi].t <= 0.03) apply({ ...evs[evi], reset: true }, 0, p0), evi++;
    if (R.arm) st.armDeg = st.armTarget;
    if (preload) {
      const id = rings.length;
      rings.push({ c: us, preload: true, track: [{ t: 0, at: "robot" }] });
      const loadDeg = R.arm ? armAngle(R.arm.load) : null;
      if (R.arm && loadDeg != null && Math.abs(st.armDeg - loadDeg) < 15) { st.armRing = id; put(id, 0, "arm"); }
      else if (R.intake) st.queue.push({ id, p: 0.5 });
    }

    const flung = (id, t, pose, why) => {
      const [x, y] = toField(pose, 0, -R.l / 2 - 6);
      put(id, t, "out", x, y, why);
    };

    const stopAt = Math.max(end, 0);
    for (let t = DT; t <= stopAt + 1e-9; t += DT) {
      const pose = poseAt(t);
      while (evi < evs.length && evs[evi].t <= t) apply(evs[evi++], t, pose);

      // The chassis shoves loose goals out of its way, except into the clamp
      // opening, where a goal slides in until it's seated: that's how a robot
      // backing into a goal lines it up before the clamp fires.
      for (let gi = 0; gi < goals.length; gi++) {
        const g = goals[gi];
        if (g.held) continue;
        const p = toRobot(pose, g.x, g.y);
        const hx = R.w / 2 + GOAL_R, hy = R.l / 2 + GOAL_R;
        if (Math.abs(p[0]) >= hx || Math.abs(p[1]) >= hy) continue;
        let q = null;
        const z = R.clamp && R.clamp.zone, c = z && boxCentre(z);
        const inSlot = z && p[0] >= z[0][0] && p[0] <= z[1][0] && Math.sign(p[1]) === Math.sign(c[1]);
        if (inSlot) {
          // seat it at the clamp, no further
          if (Math.abs(p[1]) < Math.abs(c[1])) q = [p[0], c[1]];
        } else {
          const ox = hx - Math.abs(p[0]), oy = hy - Math.abs(p[1]);
          q = ox < oy ? [Math.sign(p[0] || 1) * hx, p[1]] : [p[0], Math.sign(p[1] || 1) * hy];
        }
        if (!q) continue;
        let [nx, ny] = toField(pose, q[0], q[1]);
        const lim = HALF - GOAL_R;
        nx = Math.max(-lim, Math.min(lim, nx));
        ny = Math.max(-lim, Math.min(lim, ny));
        if (Math.hypot(nx - g.x, ny - g.y) > 0.05) { g.x = nx; g.y = ny; g.track.push({ t, held: false, x: nx, y: ny }); }
      }

      // held goal rides along
      if (st.goal >= 0) {
        const c = boxCentre(R.clamp.zone);
        const [gx, gy] = toField(pose, c[0], c[1]);
        const g = goals[st.goal];
        g.x = gx; g.y = gy;
        g.track.push({ t, held: true, x: gx, y: gy });
      }

      if (R.intake) {
        // pick up: the top ring of any stack under the intake
        if (st.intake > RING_ON && st.queue.length < R.intake.capacity && t - st.lastPick >= R.intake.pickGap) {
          for (const s of stacks) {
            if (!s.ids.length) continue;
            // the intake gets a ring as soon as any of it is in the mouth
            if (!inBox(toRobot(pose, s.x, s.y), R.intake.zone, RING_R * 0.7)) continue;
            const id = s.ids.pop();
            st.queue.push({ id, p: 0 });
            put(id, t, "robot");
            st.lastPick = t;
            if (intakeEvent >= 0) picked[intakeEvent] = (picked[intakeEvent] || 0) + 1;
            break;
          }
        }
        // conveyor
        if (Math.abs(st.intake) > RING_ON) {
          const dp = (st.intake * DT) / R.intake.transfer;
          for (let i = 0; i < st.queue.length; i++) {
            const q = st.queue[i];
            q.p = Math.min(1, q.p + dp);
            if (q.p <= 0) {                              // spat out the front
              const [x, y] = toField(pose, 0, R.l / 2 + 4);
              const s = { x, y, ids: [q.id] };
              stacks.push(s);
              put(q.id, t, "field", x, y);
              st.queue.splice(i--, 1);
            }
          }
        }
        // the ring at the top goes somewhere
        const top = st.queue[0];
        if (top && top.p >= 1) {
          const c = rings[top.id].c;
          const loadDeg = R.arm ? armAngle(R.arm.load) : null;
          if (st.until > 0 && c === us) {
            st.untilSeen++;
            if (st.untilSeen >= st.until) { st.intake = 0; st.until = 0; }   // stop and keep it
            top.p = 0.999;
          } else if (R.arm && st.armRing < 0 && loadDeg != null && Math.abs(st.armDeg - loadDeg) < 15) {
            st.armRing = top.id; put(top.id, t, "arm"); st.queue.shift();
          } else if (st.sort && c !== us) {
            flung(top.id, t, pose, "sorted"); st.queue.shift();
          } else if (st.goal >= 0 && goals[st.goal].rings.length < 6) {
            goals[st.goal].rings.push(top.id); put(top.id, t, "goal", 0, 0, st.goal); st.queue.shift();
          } else if (st.goal < 0) {
            flung(top.id, t, pose, "no goal"); st.queue.shift();
          } else {
            flung(top.id, t, pose, "goal full"); st.queue.shift();
          }
        }
      }

      if (R.arm) {
        const step = R.arm.dps * DT;
        const before = st.armDeg;
        st.armDeg += Math.max(-step, Math.min(step, st.armTarget - st.armDeg));
        if (before < R.arm.scoreDeg && st.armDeg >= R.arm.scoreDeg && st.armRing >= 0) {
          // swinging up through the stake: is one in reach?
          let hit = -1;
          stakes.forEach((s, i) => {
            if (hit < 0 && inBox(toRobot(pose, s.x, s.y), R.arm.reach, 1.0)) hit = i;
          });
          const ev = st.armEvent;
          if (hit >= 0 && stakes[hit].rings.length < stakes[hit].cap) {
            stakes[hit].rings.push(st.armRing); put(st.armRing, t, "stake", stakes[hit].x, stakes[hit].y, hit);
            if (ev != null) outcome[ev] = { ok: true, text: hit < 2 ? "alliance stake" : "wall stake" };
          } else {
            const [x, y] = toField(pose, 0, R.l / 2 + 6);
            put(st.armRing, t, "out", x, y, "missed stake");
            if (ev != null) outcome[ev] = { ok: false, text: "no stake in reach" };
          }
          st.armRing = -1;
        }
      }
    }

    for (const [k, n] of Object.entries(picked)) {
      const o = outcome[k] || { ok: null, text: "" };
      outcome[k] = { ok: n > 0 ? true : o.ok, text: n > 0 ? `+${n} ring${n > 1 ? "s" : ""}` : o.text === "intake on" ? "no rings" : o.text };
    }

    const result = { layout, alliance: us, rings, goals, stakes, outcome, robot: R, end: stopAt };
    result.final = scoreAt(result, Math.min(budget || stopAt, stopAt), poseAt);
    return result;
  })HTML",
R"HTML(

  // ---------------------------------------------------------------- state & score
  function ringAt(ring, t) {
    let s = ring.track[0];
    for (const e of ring.track) { if (e.t <= t + 1e-9) s = e; else break; }
    return s;
  }
  function goalAt(goal, t) {
    // tracks are appended in time order; binary search the last entry <= t
    const tr = goal.track;
    let lo = 0, hi = tr.length - 1;
    while (lo < hi) { const m = (lo + hi + 1) >> 1; if (tr[m].t <= t + 1e-9) lo = m; else hi = m - 1; }
    return tr[lo];
  }

  // Everything drawable at time t: loose rings, goals with their rings, stakes.
  function stateAt(res, t) {
    const loose = new Map();           // "x,y" -> { x, y, cs: [] }
    const goals = res.goals.map((g) => { const s = goalAt(g, t); return { x: s.x, y: s.y, held: s.held, rings: [] }; });
    const stakes = res.stakes.map((s) => ({ x: s.x, y: s.y, rings: [] }));
    const inRobot = [];
    let armRing = null;
    for (const r of res.rings) {
      const s = ringAt(r, t);
      if (s.at === "field") {
        const key = s.x.toFixed(2) + "," + s.y.toFixed(2);
        if (!loose.has(key)) loose.set(key, { x: s.x, y: s.y, cs: [] });
        loose.get(key).cs.push(r.c);
      } else if (s.at === "goal") goals[s.ref].rings.push(r.c);
      else if (s.at === "stake") stakes[s.ref].rings.push(r.c);
      else if (s.at === "robot") inRobot.push(r.c);
      else if (s.at === "arm") armRing = r.c;
    }
    // ring order on a goal/stake = order they were scored
    const order = (list, kind) => {
      list.forEach((el, i) => {
        const ids = res.rings.map((r, id) => [r, id]).filter(([r]) => { const s = ringAt(r, t); return s.at === kind && s.ref === i; });
        ids.sort((a, b) => ringAt(a[0], t).t - ringAt(b[0], t).t);
        el.rings = ids.map(([r]) => r.c);
      });
    };
    order(goals, "goal");
    order(stakes, "stake");
    return { loose: [...loose.values()], goals, stakes, inRobot, armRing };
  }

  // Points for both colours at time t, plus the auton win point checklist.
  function scoreAt(res, t, poseAt) {
    const L = LAYOUTS[res.layout];
    const S = stateAt(res, t);
    const pts = { r: 0, b: 0 }, neg = { r: 0, b: 0 };
    const counted = { r: 0, b: 0 };
    const stakeHas = { r: [], b: [] };   // stakes with >= 1 ring of that colour: positions
    const value = (cs, mult) => {
      const v = { r: 0, b: 0 };
      cs.forEach((c, i) => { v[c] += (i === cs.length - 1 ? 3 : 1) * mult; });
      return v;
    };
    S.goals.forEach((g) => {
      if (!g.rings.length) return;
      const corner = g.held ? 0 : cornerOf(L, g.x, g.y);
      const v = value(g.rings, corner > 0 ? 2 : 1);
      for (const c of ["r", "b"]) {
        if (corner < 0) neg[c] += v[c]; else pts[c] += v[c];
        if (g.rings.includes(c)) stakeHas[c].push(g.x);
      }
      g.rings.forEach((c) => counted[c]++);
    });
    S.stakes.forEach((s, i) => {
      const own = L.stakes[i].only;
      const cs = own ? s.rings.filter((c) => c === own) : s.rings;
      if (!cs.length) return;
      const v = value(cs, 1);
      for (const c of ["r", "b"]) { pts[c] += v[c]; if (cs.includes(c)) stakeHas[c].push(s.x); }
      cs.forEach((c) => counted[c]++);
    });
    for (const c of ["r", "b"]) pts[c] = Math.max(0, pts[c] - neg[c]);

    const us = res.alliance, side = us === "b" ? 1 : -1;
    const out = { us: pts[us], them: pts[us === "b" ? "r" : "b"], rings: counted[us], points: pts };
    if (L.match && poseAt) {
      const pose = poseAt(t);
      const pts2 = res.robot.outline.map(([x, y]) => toField(pose, x, y));
      const xs = pts2.map((p) => p[0] * side);
      const onLadder = pts2.some(([x, y]) => Math.abs(x) + Math.abs(y) <= 25) ||
        (res.robot.arm && [[0, res.robot.arm.reach[1][1]]].map(([x, y]) => toField(pose, x, y)).some(([x, y]) => Math.abs(x) + Math.abs(y) <= 25));
      out.awp = {
        rings: counted[us] >= 3,
        stakes: stakeHas[us].filter((x) => x * side > 0).length >= 2,
        line: !(Math.min(...xs) <= L.startingLine + 1 && Math.max(...xs) >= L.startingLine - 1),
        ladder: onLadder,
      };
      out.awp.all = out.awp.rings && out.awp.stakes && out.awp.line && out.awp.ladder;
    }
    return out;
  }

  const api = { LAYOUTS, supported, compile, events, run, stateAt, scoreAt, evalNumber, toRobot, toField };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.VexGame = api;
})(typeof window !== "undefined" ? window : globalThis);
</script>
<script>
"use strict";
const D = /*REPORT_DATA*/null;
const F = window.VexField;
const $ = (id) => document.getElementById(id);
const dpr = () => window.devicePixelRatio || 1;

// ------------------------------------------------------------------ state
const KEY = "sysvrc:" + D.name;
const store = { get(k, d) { try { const v = localStorage.getItem(KEY + ":" + k); return v == null ? d : JSON.parse(v); } catch { return d; } },
                set(k, v) { try { localStorage.setItem(KEY + ":" + k, JSON.stringify(v)); } catch {} } };
// The side the routine's numbers are written for. A field start on the left
// half is red's side even in a .blue file: lots of teams write one side and
// mirror the turns with sgn, so x never flips.
const baseSide = D.field_start ? (D.field_start[0] < 0 ? "red" : "blue") : D.alliance || "red";
const S = {
  t: 0, playing: false, speed: 1,
  layout: store.get("layout", D.field),
  side: store.get("side", D.alliance || baseSide),
  units: store.get("units", "in"),
  sel: -1,                                            // selected action index
  place: null,                                        // field pose of the start, on the base side
  placed: false,                                      // has the user put it somewhere
};
const T = { end: D.stats.nominal, max: Math.max(D.stats.worst, D.budget, D.stats.total) + 0.6 };

// Where the routine starts on the field. A real field start (walls were
// simulated) is fixed. Otherwise: wherever the user dragged it last, or the
// routine's own odom_xyt_set if it looks like field coordinates, or a guess
// that keeps the whole path inside the walls.
(function initPlace() {
  if (D.field_start) { S.place = D.field_start.slice(); S.placed = true; return; }
  const saved = store.get("place", null);
  if (saved) { S.place = saved; S.placed = true; return; }
  const [x, y] = D.start;
  if ((x || y) && Math.abs(x) <= 66 && Math.abs(y) <= 66) { S.place = D.start.slice(); S.placed = true; return; }
  S.place = guessPlace();
})();

// Most routines zero odom at the start, so the code frame says nothing about
// where on the field they begin. Pick the start that keeps the path inside the
// walls, on the routine's own side, trusting the code's heading first.
function guessPlace() {
  const side = baseSide === "blue" ? 1 : -1, lim = F.HALF - 8, h0 = D.start[2];
  // after a drive_set push with no walls the path is meaningless; fit what's before it
  const push = D.instrs.find((r) => r.text.startsWith("drive_set(") && r.t >= 0);
  const cut = push ? Math.max(2, Math.floor(push.t / D.dt) + 1) : D.path.length;
  const pts = D.path.slice(0, cut).filter((_, i) => i % 2 === 0);
  const turns = [0, 90, -90, 180];
  for (let d = 15; d < 180; d += 15) if (d % 90) turns.push(d, -d);
  let best = null;
  for (const dh of turns) {
    let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity;
    for (const p of pts) {
      const q = F.codeToField(p, D.start, [0, 0, h0 + dh]);
      x0 = Math.min(x0, q[0]); x1 = Math.max(x1, q[0]); y0 = Math.min(y0, q[1]); y1 = Math.max(y1, q[1]);
    }
    // the start may sit anywhere in [lo, hi] on each axis and the path stays in
    const fit = (lo, hi, want) => (lo <= hi ? [Math.max(lo, Math.min(hi, want)), 0] : [(lo + hi) / 2, lo - hi]);
    const [sx, ox] = fit(-lim - x0, lim - x1, side * 64);
    const [sy, oy] = fit(-lim - y0, lim - y1, (-lim - y0 + lim - y1) / 2);
    const cost = (ox + oy) * 100 + (sx * side < 0 ? 500 : 0) + (dh === 0 ? 0 : dh % 90 === 0 ? 20 : 40) + Math.abs(sx - side * 64) * 0.1;
    if (!best || cost < best.cost) best = { cost, p: [Math.round(sx), Math.round(sy), h0 + dh] };
  }
  return best.p;
}

// code frame -> field, then mirror if showing the other alliance
const origin = D.field_start || D.start;
function toField(p) {
  let q = F.codeToField(p, origin, S.place);
  if (S.side !== baseSide) q = F.mirror(q);
  return q;
}
const sideColor = () => (S.side === "blue" ? F.BLUE : F.RED);

// ------------------------------------------------------------------ game elements
// With a robot.json (auton_check --robot), work out what the routine does to
// the rings and goals: the clean run drives the animation, the varied runs say
// how often it really scores that. Redone whenever the start, side or field
// changes, which is cheap because the driving was already simulated.
const GAME = window.VexGame;
const robot = D.spec && GAME ? GAME.compile(D.spec) : null;
const actionTexts = D.actions.map((a) => D.instrs[a.i].text.replace(/^action\("(.*)"\)$/, "$1"));
let game = null;            // the clean run
let gameRuns = [];          // the varied runs
const gameOn = () => !!robot && GAME.supported(S.layout);
let ghostTimer = 0;
function runGame() {
  game = null;
  gameRuns = [];
  clearTimeout(ghostTimer);
  if (gameOn()) {
    game = GAME.run({ layout: S.layout, robot, alliance: S.side, budget: D.budget, end: D.stats.total,
                      poseAt: (t) => toField(sampleAt(D.path, D.dt, t)),
                      events: GAME.events(robot, actionTexts, D.actions.map((a) => a.t)) });
    ghostTimer = setTimeout(() => {
      gameRuns = D.ghosts.map((run, g) => GAME.run({
        layout: S.layout, robot, alliance: S.side, budget: D.budget, end: run.length * D.gdt,
        poseAt: (t) => toField(sampleAt(run, D.gdt, t)),
        events: GAME.events(robot, actionTexts, (D.gact && D.gact[g]) || []) }));
      renderScore();
      renderCode();
      renderWhy();
    }, 150);
  }
  renderScore();
}
// How many varied runs got the same result from mechanism call k.
function hitRate(k) {
  const outs = gameRuns.map((r) => r.outcome[k]).filter((o) => o && o.ok !== null && o.ok !== undefined);
  if (!outs.length) return null;
  return outs.filter((o) => o.ok).length / outs.length;
}

// ------------------------------------------------------------------ header
$("name").textContent = D.name;
$("sub").textContent = `${D.runs} runs`;
for (const [k, L] of Object.entries(F.LAYOUTS)) {
  const o = document.createElement("option"); o.value = k; o.textContent = L.name; $("layout").appendChild(o);
}
$("layout").value = S.layout;
$("layout").onchange = (e) => { S.layout = e.target.value; store.set("layout", S.layout); fieldCache = null; runGame(); renderCode(); draw(); };
function segInit(id, key, after) {
  const el = $(id);
  const paint = () => el.querySelectorAll("button").forEach((b) => b.classList.toggle("on", b.dataset.v === S[key]));
  el.onclick = (e) => { const v = e.target.dataset && e.target.dataset.v; if (!v) return; S[key] = v; store.set(key, v); paint(); after && after(); draw(); };
  paint();
}
segInit("side", "side", () => { runGame(); renderCode(); });
segInit("units", "units");

const st = D.stats;
const late = st.on_time < 100;
$("stats").innerHTML =
  `<span class="${late ? "bad" : ""}"><b>${st.on_time.toFixed(0)}%</b> on time</span>` +
  `<span>p95 <b>${st.p95.toFixed(2)}s</b></span>` +
  `<span title="end point spread, p95">±<b>${len(st.end_p95, 1)}</b></span>` +
  `<span id="score" hidden></span>`;

// Points at the buzzer in the clean run, how many varied runs match it, and
// the auton win point checklist.
function renderScore() {
  const el = $("score");
  if (!el) return;
  if (!game) { el.hidden = true; return; }
  const f = game.final;
  let html = `<b>${f.us}</b> pts`;
  const finals = gameRuns.map((r) => r.final.us);
  if (finals.length) {
    const atLeast = finals.filter((v) => v >= f.us).length / finals.length;
   )HTML",
R"HTML( html += ` <span title="varied runs scoring at least ${f.us}" class="${atLeast < 0.9 ? "bad" : ""}"><b>${Math.round(atLeast * 100)}%</b></span>`;
  }
  if (f.awp) {
    const items = [["rings", "3 alliance rings"], ["stakes", "2 stakes on our side"], ["line", "off the starting line"], ["ladder", "touching the ladder"]];
    const missing = items.filter(([k]) => !f.awp[k]).map(([, t]) => t);
    html += ` <span class="chip ${missing.length ? "miss" : "ok"}" title="${missing.length ? "missing: " + missing.join(", ") : "all four tasks done"}">AWP ${missing.length ? `${4 - missing.length}/4` : "✓"}</span>`;
  }
  el.innerHTML = html;
  el.hidden = false;
}

function len(v, d) { return F.fmtLen(v, S.units, S.units === "tiles" ? (d == null ? 2 : d + 1) : d); }

// ------------------------------------------------------------------ code rail
const code = $("code");
function exitWord(e) {
  return { small_error: "settled", big_error: "settled", passed: "passed", velocity: "stalled", timeout: "timeout", running: "" }[e] || e || "";
}
function renderCode() {
  code.innerHTML = "";
  D.instrs.forEach((r, i) => {
    const li = document.createElement("li");
    li.className = "k-" + r.kind;
    li.dataset.i = i;
    let bd = "", cls = "bd";
    if (i === st.late_i && late) { bd = `${(100 - st.on_time).toFixed(0)}% at buzzer`; cls += " late"; }
    else if (r.kind === "wait") {
      if (r.stall >= 1) { bd = `${r.stall.toFixed(0)}% stall`; cls += " warn"; }
      else bd = exitWord(r.exit);
    } else if (r.kind === "action" && r.action != null) {
      const o = game && game.outcome[r.action];
      if (o && o.text && o.ok !== null) {
        const rate = hitRate(r.action);
        bd = o.text + (rate !== null && rate < 0.98 ? ` ${Math.round(rate * 100)}%` : "");
        cls += o.ok === false ? " late" : rate !== null && rate < 0.9 ? " warn" : " ok";
      } else {
        bd = "±" + len(D.actions[r.action].p95, 1);
      }
    }
    li.innerHTML = `<span class="ln">${r.line || ""}</span><span class="g"></span><span class="tx"></span><span class="${cls}">${bd}</span>`;
    li.querySelector(".tx").textContent = r.text.replace(/^action\("(.*)"\)$/, "$1");
    li.title = r.text + (r.action != null && game && game.outcome[r.action] && game.outcome[r.action].text ? "\n" + game.outcome[r.action].text : "");
    li.onclick = () => {
      if (r.kind === "action") selectAction(r.action, true);
      else { S.sel = -1; seek(Math.max(0, r.t)); }
    };
    code.appendChild(li);
  });
  syncCode(true);
}
let lastOn = -1;
function syncCode(force) {
  let on = 0;
  for (let i = 0; i < D.instrs.length; i++) if (D.instrs[i].t >= 0 && D.instrs[i].t <= S.t + 1e-6) on = i;
  const items = code.children;
  if (on === lastOn && !force) return;
  for (let i = 0; i < items.length; i++) {
    items[i].classList.toggle("on", i === on);
    items[i].classList.toggle("done", i < on);
    const a = D.instrs[i].action;
    items[i].classList.toggle("sel", a != null && a === S.sel);
  }
  if (items[on] && (on !== lastOn || force)) items[on].scrollIntoView({ block: "nearest" });
  lastOn = on;
}

// why: the two rankings and the score spread, compact
function renderWhy() {
  const w = D.why || { spread: [], late: [] };
  const top = (xs, f) => xs.slice(0, 3).map(f).join(" · ");
  const short = (n) => n.replace("placement (heading)", "heading").replace("placement (x/y)", "placement").replace("motor response", "motors").replace("L/R mismatch", "L/R").replace("wheel slip", "slip").replace("gyro drift", "gyro");
  const rows = [];
  if (w.spread.length) rows.push(["spread", top(w.spread, ([n, v]) => `${short(n)} ${len(v, 1)}`)]);
  const lateRows = w.late.filter(([, dt]) => dt > 0.05);
  if (lateRows.length) rows.push(["late", top(lateRows, ([n, dt]) => `${short(n)} +${dt.toFixed(2)}s`)]);
  if (gameRuns.length) {
    const counts = new Map();
    for (const r of gameRuns) counts.set(r.final.us, (counts.get(r.final.us) || 0) + 1);
    const byCount = [...counts.entries()].sort((a, b) => b[1] - a[1] || b[0] - a[0]);
    rows.push(["score", byCount.slice(0, 3).map(([pts, n]) => `${pts} in ${Math.round((100 * n) / gameRuns.length)}%`).join(" · ")]);
  }
  $("why").innerHTML = rows.map(([k, v]) => `<div class="row"><span class="k">${k}</span><span>${v}</span></div>`).join("");
  $("why").hidden = !rows.length;
}

// ------------------------------------------------------------------ note (warnings + field-start helper)
function renderNote() {
  const n = $("note");
  if (!D.warnings.length || D.field_start) { n.hidden = true; return; }
  const p = S.place.map((v, i) => String(+(i < 2 ? v : F.wrapDeg(v)).toFixed(i < 2 ? 1 : 0)));
  const cmd = `--field-start ${p.join(",")}`;
  n.hidden = false;
  n.innerHTML = `<span>wall push needs a start · drag the robot, rerun with</span><code></code><button>copy</button>`;
  n.querySelector("code").textContent = cmd;
  n.querySelector("button").onclick = () => { navigator.clipboard && navigator.clipboard.writeText(cmd); n.querySelector("button").textContent = "copied"; };
}

// ------------------------------------------------------------------ geometry helpers
function sampleAt(arr, dt, t) {
  if (!arr.length) return null;
  const f = t / dt, i = Math.floor(f);
  if (i >= arr.length - 1) return arr[arr.length - 1];
  if (i < 0) return arr[0];
  const a = arr[i], b = arr[i + 1], u = f - i;
  let dh = b[2] - a[2]; if (dh > 180) dh -= 360; if (dh < -180) dh += 360;
  return [a[0] + (b[0] - a[0]) * u, a[1] + (b[1] - a[1]) * u, a[2] + dh * u];
}

// ------------------------------------------------------------------ field canvas
const fc = $("field");
let V = null, fieldCache = null, size = 0;
function layout() {
  const r = $("stage").getBoundingClientRect();
  size = Math.max(200, Math.floor(Math.min(r.width, r.height) - 16));
  fc.style.width = fc.style.height = size + "px";
  fc.width = fc.height = Math.round(size * dpr());
  V = F.view(size, 82);
  fieldCache = null;
}
function drawStatic() {
  const c = document.createElement("canvas");
  c.width = c.height = Math.round(size * dpr());
  const g = c.getContext("2d");
  g.scale(dpr(), dpr());
  F.drawField(g, V, S.layout, { elements: !gameOn() });
  fieldCache = c;
}

function draw() {
  if (!V) return;
  if (!fieldCache) drawStatic();
  const g = fc.getContext("2d");
  g.setTransform(1, 0, 0, 1, 0, 0);
  g.drawImage(fieldCache, 0, 0);
  g.scale(dpr(), dpr());
  const P = (p) => V.px(p[0], p[1]);
  const path = D.path.map(toField);

  // the clean run's path: faint ahead of the robot, solid behind it
  const k = Math.min(path.length - 1, Math.floor(S.t / D.dt));
  g.lineJoin = g.lineCap = "round";
  g.strokeStyle = "rgba(245,184,0,0.32)"; g.lineWidth = 2;
  poly(g, path, 0, path.length - 1, P);
  g.strokeStyle = "#f5b800"; g.lineWidth = 2.5;
  poly(g, path, 0, k, P);

  // mechanism calls along the path
  D.actions.forEach((a, i) => {
    const q = toField([a.at[0], a.at[1], 0]);
    const [x, y] = P(q);
    g.save(); g.translate(x, y); g.rotate(Math.PI / 4);
    g.fillStyle = i === S.sel ? "#1fc8f0" : "rgba(31,200,240,0.75)";
    g.strokeStyle = "#14171b"; g.lineWidth = 2;
    const r = i === S.sel ? 5 : 3.5;
    g.beginPath(); g.rect(-r, -r, 2 * r, 2 * r); g.stroke(); g.fill();
    g.restore();
  });

  // the selected call: where it fired in every run, and the p95 circle
  let callout = null;
  if (S.sel >= 0) {
    const a = D.actions[S.sel];
    g.fillStyle = "rgba(31,200,240,0.55)";
    for (const pt of a.pts) { const [x, y] = P(toField([pt[0], pt[1], 0])); g.beginPath(); g.arc(x, y, 2, 0, Math.PI * 2); g.fill(); }
    const [cx, cy] = P(toField([a.at[0], a.at[1], 0]));
    g.setLineDash([4, 3]); g.strokeStyle = "#1fc8f0"; g.lineWidth = 1.5;
    g.beginPath(); g.arc(cx, cy, Math.max(3, a.p95 * V.s), 0, Math.PI * 2); g.stroke(); g.setLineDash([]);
    const o = game && game.outcome[S.sel];
    callout = [actionTexts[S.sel] + "  ±" + len(a.p95, 1) + (o && o.text ? "  · " + o.text : ""), cx, cy - Math.max(3, a.p95 * V.s) - 10];
  }

  // rings and goals as the clean run left them at this moment
  const gs = game ? GAME.stateAt(game, S.t) : null;
  if (gs) F.drawElements(g, V, S.layout, gs);

  // every varied run at this moment
  const [w, l] = D.robot;
  const outline = robot ? robot.outline : null;
  for (const run of D.ghosts) {
    const p = sampleAt(run, D.gdt, S.t);
    if (p) F.drawRobot(g, V, toField(p), { w, l, outline, stroke: "rgba(255,255,255,0.22)", width: 1 });
  }

  // where it started, once it has left
  if (S.t > 0.05) F.drawRobot(g, V, toField(D.path[0]), { w, l, outline, stroke: "rgba(255,255,255,0.35)", width: 1 });

  // the clean run, with where its mechanisms reach
  const me = sampleAt(D.path, D.dt, S.t);
  const zones = [];
  if (robot && robot.intake) zones.push({ box: robot.intake.zone, color: "rgba(31,200,240,0.9)" });
  if (robot && robot.clamp) zones.push({ box: robot.clamp.zone, color: "rgba(245,184,0,0.9)" });
  F.drawRobot(g, V, toField(me), { w, l, outline, zones, fill: sideColor(), stroke: "#fff", front: "#fff", width: 1.5, alpha: 0.95 });
  if (gs && (gs.inRobot.length || gs.armRing)) {
    const q = toField(me);
    if (gs.inRobot.length) F.drawStack(g, V, q[0], q[1], gs.inRobot, 0.8);
    if (gs.armRing) {
      const [ax, ay] = GAME.toField(q, 0, l / 2 + 2);
      F.drawStack(g, V, ax, ay, [gs.armRing], 0.8);
    }
  }
  if (callout) label(g, ...callout);
  hud(me);
}
function poly(g, pts, a, b, P) {
  if (b <= a) return;
  g.beginPath();
  for (let i = a; i <= b; i++) { const [x, y] = P(pts[i]); i === a ? g.moveTo(x, y) : g.lineTo(x, y); }
  g.stroke();
}
function label(g, text, x, y) {
  g.font = "600 11px " + getComputedStyle(document.body).getPropertyValue("--mono");
  g.textBaseline = "middle";
  const wpx = g.measureText(text).width;
  x = Math.max(4, Math.min(size - 4 - wpx, x - wpx / 2));
  y = Math.max(10, y);
  g.lineWidth = 4; g.strokeStyle = "#14171b"; g.strokeText(text, x, y);
  g.fillStyle = "#e7eaee"; g.fillText(text, x, y);
}

let hover = null;
function hud(me) {
  const q = toField(me);
  const parts = [`<span>x <b>${len(q[0])}</b></span>`, `<span>y <b>${len(q[1])}</b></span>`, `<span>θ <b>${F.wrapDeg(q[2]).toFixed(0)}°</b></span>`];
  if (hover) parts.push(`<span style="color:var(--muted)">cursor ${len(hover[0])}, ${len(hover[1])}</span>`);
  $("hud").innerHTML = parts.join("");
}

// ------------------------------------------------------------------ dragging the start
let drag = null;
const hint = $("hint");
function overStart(px, py) {
  const s = toField(D.path[0]);
  const [x, y] = V.px(s[0], s[1]);
  return Math.hypot(px - x, py - y) < (D.robot[0] / 2 + 3) * V.s;
}
function showHint() {
  if (S.placed || D.field_start || S.t > 0.05) { hint.hidden = true; return; }
  const s = toField(D.path[0]);
  const [x, y] = V.px(s[0], s[1]);
  const r = $("field").getBoundingClientRect(), st2 = $("stage").getBoundingClientRect();
  hint.hidden = false;
  hint.textContent = "drag to your start · [ ] to rotate";
  const left = r.left - st2.left + x - hint.offsetWidth / 2;
  hint.style.left = Math.max(6, Math.min(st2.width - hint.offsetWidth - 6, left)) + "px";
  hint.style.top = (r.top - st2.top + y + (D.robot[1] / 2 + 6) * V.s) + "px";
}
fc.addEventListener("pointermove", (e) => {
  const r = fc.getBoundingClientRect(), px = e.clientX - r.left, py = e.clientY - r.top;
  hover = V.inches(px, py);
  if (drag) {
    let [x, y] = V.inches(px - drag.dx, py - drag.dy);
    if (S.side !== baseSide) x = -x;                 // stored on the base side
    const lim = F.HALF - D.robot[0] / 2;
    S.place = [Math.max(-lim, Math.min(lim, Math.round(x * 2) / 2)), Math.max(-lim, Math.min(lim, Math.round(y * 2) / 2)), S.place[2]];
    S.placed = true; store.set("place", S.place); renderNote(); showHint(); runGame();
  }
  fc.style.cursor = drag ? "grabbing" : !D.field_start && overStart(px, py) ? "grab" : "default";
  draw();
});
fc.addEventListener("pointerleave", () => { hover = null; d)HTML",
R"HTML(raw(); });
fc.addEventListener("pointerdown", (e) => {
  const r = fc.getBoundingClientRect(), px = e.clientX - r.left, py = e.clientY - r.top;
  if (D.field_start || !overStart(px, py)) return;
  const s = toField(D.path[0]);
  const [x, y] = V.px(s[0], s[1]);
  drag = { dx: px - x, dy: py - y };
  fc.setPointerCapture(e.pointerId);
});
fc.addEventListener("pointerup", () => { drag = null; });
fc.addEventListener("dblclick", (e) => {
  const r = fc.getBoundingClientRect();
  if (D.field_start || !overStart(e.clientX - r.left, e.clientY - r.top)) return;
  try { localStorage.removeItem(KEY + ":place"); } catch {}
  location.reload();
});
function rotateStart(d) {
  if (D.field_start) return;
  S.place = [S.place[0], S.place[1], S.place[2] + (S.side !== baseSide ? -d : d)];
  S.placed = true; store.set("place", S.place); renderNote(); showHint(); runGame(); renderCode(); draw();
}

// ------------------------------------------------------------------ timeline
const tl = $("tl");
let TLW = 0;
function tlLayout() {
  const r = tl.getBoundingClientRect();
  TLW = r.width;
  tl.width = Math.round(r.width * dpr()); tl.height = Math.round(56 * dpr());
}
const tx = (t) => 8 + (t / T.max) * (TLW - 16);
const tt = (x) => Math.max(0, Math.min(T.max, ((x - 8) / (TLW - 16)) * T.max));
const BIN = 0.1;
const bins = (() => {
  const b = new Map();
  for (const f of D.finish) { const k = Math.floor(f / BIN); b.set(k, (b.get(k) || 0) + 1); }
  return b;
})();
const binMax = Math.max(1, ...bins.values());
function drawTimeline() {
  const g = tl.getContext("2d");
  g.setTransform(dpr(), 0, 0, dpr(), 0, 0);
  g.clearRect(0, 0, TLW, 56);
  const base = 40;
  // auton period
  g.fillStyle = "rgba(255,255,255,0.045)";
  g.fillRect(tx(0), 6, tx(D.budget) - tx(0), base - 6);
  // ticks
  g.fillStyle = "#6c7480"; g.font = "10px " + getComputedStyle(document.body).getPropertyValue("--mono");
  g.textAlign = "center"; g.textBaseline = "top";
  const step = T.max > 40 ? 10 : T.max > 20 ? 5 : 1;
  for (let s = 0; s <= T.max; s += step) {
    g.fillRect(tx(s), base, 1, 4);
    if (s % (step === 1 ? 5 : step) === 0) g.fillText(String(s), tx(s), base + 6);
  }
  g.fillStyle = "#252a31"; g.fillRect(tx(0), base, tx(T.max) - tx(0), 1);
  // when runs finished
  for (const [k, n] of bins) {
    const t0 = k * BIN, h = 4 + (n / binMax) * 22;
    g.fillStyle = t0 >= D.budget ? "rgba(229,83,75,0.85)" : "rgba(166,174,184,0.55)";
    const x = tx(t0), w = Math.max(1, tx(t0 + BIN) - x - 1);
    g.fillRect(x, base - h, w, h);
  }
  // buzzer
  g.strokeStyle = "#e5534b"; g.lineWidth = 1; g.setLineDash([3, 3]);
  g.beginPath(); g.moveTo(tx(D.budget) + 0.5, 4); g.lineTo(tx(D.budget) + 0.5, base); g.stroke(); g.setLineDash([]);
  // mechanism calls
  D.actions.forEach((a, i) => {
    g.fillStyle = i === S.sel ? "#1fc8f0" : "rgba(31,200,240,0.5)";
    const x = tx(a.t);
    g.beginPath(); g.moveTo(x, base + 1); g.lineTo(x - 3, base + 6); g.lineTo(x + 3, base + 6); g.closePath(); g.fill();
  });
  // playhead
  const x = tx(S.t);
  g.fillStyle = "#f5b800"; g.fillRect(x - 1, 2, 2, base);
  g.beginPath(); g.arc(x, 4, 4, 0, Math.PI * 2); g.fill();
}
let scrubbing = false;
tl.addEventListener("pointerdown", (e) => { scrubbing = true; tl.setPointerCapture(e.pointerId); pause(); seek(tt(e.offsetX)); });
tl.addEventListener("pointermove", (e) => {
  if (scrubbing) seek(tt(e.offsetX));
  const t = tt(e.offsetX), n = bins.get(Math.floor(t / BIN)) || 0;
  const tip = $("tip");
  tip.style.display = "block";
  tip.textContent = `${t.toFixed(2)}s` + (n ? ` · ${n} run${n > 1 ? "s" : ""} finish` : "") + (t > D.budget ? " · after buzzer" : "");
  tip.style.left = e.clientX + 10 + "px"; tip.style.top = e.clientY - 28 + "px";
});
tl.addEventListener("pointerup", () => { scrubbing = false; });
tl.addEventListener("pointerleave", () => { $("tip").style.display = "none"; });

// ------------------------------------------------------------------ playback
function seek(t) {
  S.t = Math.max(0, Math.min(T.max, t));
  $("clock").textContent = S.t.toFixed(2);
  syncCode(); draw(); drawTimeline(); showHint();
  if (!S.playing) linkHere();
}
// #t=9.3&a=12 opens the report at that moment with that call selected
function linkHere() {
  try { history.replaceState(null, "", "#t=" + S.t.toFixed(2) + (S.sel >= 0 ? "&a=" + S.sel : "")); } catch {}
}
let last = 0;
function frame(now) {
  if (!S.playing) return;
  const dt = (now - last) / 1000; last = now;
  if (S.t >= T.max) { pause(); return; }
  seek(S.t + dt * S.speed);
  requestAnimationFrame(frame);
}
function play() { if (S.t >= T.max - 0.01) S.t = 0; S.playing = true; last = performance.now(); $("playIcon").setAttribute("d", "M2 1h3v10H2zM7 1h3v10H7z"); requestAnimationFrame(frame); }
function pause() { S.playing = false; $("playIcon").setAttribute("d", "M2 1l9 5-9 5z"); }
$("play").onclick = () => (S.playing ? pause() : play());
const speeds = [0.5, 1, 2, 4];
$("speed").onclick = () => { S.speed = speeds[(speeds.indexOf(S.speed) + 1) % speeds.length]; $("speed").textContent = S.speed + "×"; };

function selectAction(i, jump) {
  S.sel = S.sel === i ? -1 : i;
  if (S.sel >= 0 && jump) seek(D.actions[i].t); else { syncCode(true); draw(); drawTimeline(); linkHere(); }
}

window.addEventListener("keydown", (e) => {
  if (e.target.tagName === "SELECT") return;
  if (e.key === " ") { e.preventDefault(); S.playing ? pause() : play(); }
  else if (e.key === "ArrowRight") { pause(); seek(S.t + (e.shiftKey ? 1 : 0.1)); }
  else if (e.key === "ArrowLeft") { pause(); seek(S.t - (e.shiftKey ? 1 : 0.1)); }
  else if (e.key === "Home") seek(0);
  else if (e.key === "End") seek(T.end);
  else if (e.key === "[") rotateStart(e.shiftKey ? -1 : -5);
  else if (e.key === "]") rotateStart(e.shiftKey ? 1 : 5);
  else if (e.key === "." || e.key === ",") {
    if (!D.actions.length) return;
    const dir = e.key === "." ? 1 : -1;
    const cur = S.sel >= 0 ? S.sel : dir > 0 ? -1 : D.actions.length;
    const n = Math.max(0, Math.min(D.actions.length - 1, cur + dir));
    S.sel = -1; selectAction(n, true);
  }
});

// ------------------------------------------------------------------ go
function resize() { layout(); tlLayout(); draw(); drawTimeline(); showHint(); }
window.addEventListener("resize", resize);
runGame();
renderCode();
renderWhy();
renderNote();
resize();
(function fromLink() {
  const h = new URLSearchParams(location.hash.slice(1));
  const a = parseInt(h.get("a"), 10);
  if (a >= 0 && a < D.actions.length) S.sel = a;
  seek(parseFloat(h.get("t")) || 0);
})();
</script>
</body>
</html>
)HTML",
};

inline std::string reportTemplate() {
    std::string s;
    for (const char* p : kReportTemplateParts) s += p;
    return s;
}
