#!/usr/bin/env python3
"""Regenerate the files that are built from web/.

  web/report.html + field.js + game.js  ->  core/tools/report_template.hpp
  web/field.js, web/game.js             ->  sim/src/visbot_dash/web/

auton_check has no runtime dependencies, so the report page is compiled into
it as one string with field.js and game.js inlined. Run this after editing anything in
web/; `--check` exits 1 if the generated files are stale (CI runs that).
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
HPP = ROOT / "core" / "tools" / "report_template.hpp"
DASH_WEB = ROOT / "sim" / "src" / "visbot_dash" / "web"

HEADER = """\
// GENERATED by tools/build_web.py from web/report.html, field.js and game.js.
// Edit those, then run `python3 tools/build_web.py`.
//
// Self-contained: no CDN, no network, opens from a file on any laptop at a
// competition. auton_check replaces the REPORT_DATA marker with the run's JSON.
//
// In pieces because one string literal this long is past what compilers have
// to accept (MSVC stops at 16 KB a literal).
#pragma once

#include <string>

inline const char* const kReportTemplateParts[] = {
"""
FOOTER = """};

inline std::string reportTemplate() {
    std::string s;
    for (const char* p : kReportTemplateParts) s += p;
    return s;
}
"""
CHUNK = 12000   # bytes per literal, well under MSVC's 16380


def outputs():
    field = (WEB / "field.js").read_text()
    game = (WEB / "game.js").read_text()
    page = (WEB / "report.html").read_text()
    for marker in ("/*FIELD_JS*/", "/*GAME_JS*/", "/*REPORT_DATA*/null"):
        if marker not in page:
            sys.exit(f"web/report.html is missing its {marker} marker")
    page = page.replace("/*FIELD_JS*/", "\n" + field).replace("/*GAME_JS*/", "\n" + game)
    if ')HTML"' in page:
        sys.exit('web/ contains )HTML" which would end the C++ raw string early')
    data = page.encode()
    parts = []
    i = 0
    while i < len(data):
        j = min(len(data), i + CHUNK)
        while j < len(data) and (data[j] & 0xC0) == 0x80:     # don't split a UTF-8 character
            j -= 1
        parts.append('R"HTML(' + data[i:j].decode() + ')HTML"')
        i = j
    hpp = HEADER + ",\n".join(parts) + ",\n" + FOOTER
    return {HPP: hpp, DASH_WEB / "field.js": field, DASH_WEB / "game.js": game}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = ap.parse_args()

    stale = []
    for path, text in outputs().items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    if args.check and stale:
        print("stale (run python3 tools/build_web.py):", *stale, sep="\n  ")
        return 1
    for p in stale:
        print("wrote", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
