#!/usr/bin/env python3
"""Regenerate the files that are built from web/.

  web/report.html + web/field.js  ->  core/tools/report_template.hpp
  web/field.js                    ->  sim/src/visbot_dash/web/field.js

auton_check has no runtime dependencies, so the report page is compiled into
it as one string with field.js inlined. Run this after editing anything in
web/; `--check` exits 1 if the generated files are stale (CI runs that).
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
HPP = ROOT / "core" / "tools" / "report_template.hpp"
DASH_FIELD = ROOT / "sim" / "src" / "visbot_dash" / "web" / "field.js"

HEADER = """\
// GENERATED by tools/build_web.py from web/report.html and web/field.js.
// Edit those, then run `python3 tools/build_web.py`.
//
// Self-contained: no CDN, no network, opens from a file on any laptop at a
// competition. auton_check replaces the REPORT_DATA marker with the run's JSON.
#pragma once

inline const char* const kReportTemplate = R"HTML("""
FOOTER = ')HTML";\n'


def outputs():
    field = (WEB / "field.js").read_text()
    page = (WEB / "report.html").read_text()
    if "/*FIELD_JS*/" not in page or "/*REPORT_DATA*/null" not in page:
        sys.exit("web/report.html is missing a /*FIELD_JS*/ or /*REPORT_DATA*/null marker")
    page = page.replace("/*FIELD_JS*/", "\n" + field)
    if ')HTML"' in page:
        sys.exit('web/ contains )HTML" which would end the C++ raw string early')
    return {HPP: HEADER + page + FOOTER, DASH_FIELD: field}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = ap.parse_args()

    stale = []
    for path, text in outputs().items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    if args.check and stale:
        print("stale (run python3 tools/build_web.py):", *stale, sep="\n  ")
        return 1
    for p in stale:
        print("wrote", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
